### ISSUE TITLE
weworkmeteor.com

### ISSUE THREAD

**Issue by fede-rodes** [jensamunch/pricing-agent#1]
Hi Jens,

I saw your post on weworkmeteor.com about a '2-page app - simulator with visualisation'. I think the app you are describing could be delivered within one week using Meteor + React. I would charge 180 euros. Here is my profile: https://www.upwork.com/freelancers/~0115030d6df16fa154 

Please, let me know if the proposal fits your needs. Looking forward to work together. 

Best, 

Federico

**Comment by jensamunch** [comment]
Hey,

Sounds great - like your site and sounds like it could work. Here is more
detailed PDF attached - does this still make sense to you and is
interesting?
Could talk on Skype if you want?

My email is jens.a.munch@gmail.com

J
